services:
  scanner:
    build: .
    image: cwavesoftware/docker-scan-project:latest
    platform: linux/arm/v7 # Ensures compatibility with ARM architecture
    container_name: network-scanner
    restart: always # Ensures the container restarts automatically
    network_mode: host # Allows the container to access the host's network
    privileged: true # Grants the container extended privileges
    volumes:
      - /data:/data
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_INFO_CHANNEL=${SLACK_INFO_CHANNEL}
      - SLACK_ERROR_CHANNEL=${SLACK_ERROR_CHANNEL}
      - SLACK_DEBUG_CHANNEL=${SLACK_DEBUG_CHANNEL}